figure
hold on

for i = 1 : length(mnodes)
    
    x = mnodes(i).x(1);
    y = mnodes(i).x(2);
    theta = mnodes(i).theta;
    lx = mnodes(i).l(1);
    ly = mnodes(i).l(2);
    
    xd = [x+lx/2*cos(theta)-ly/2*sin(theta),...
        x-lx/2*cos(theta)-ly/2*sin(theta),...
        x-lx/2*cos(theta)+ly/2*sin(theta),...
        x+lx/2*cos(theta)+ly/2*sin(theta),...
        x+lx/2*cos(theta)-ly/2*sin(theta);...
        y+lx/2*sin(theta)+ly/2*cos(theta),...
        y-lx/2*sin(theta)+ly/2*cos(theta),...
        y-lx/2*sin(theta)-ly/2*cos(theta),...
        y+lx/2*sin(theta)-ly/2*cos(theta),...
        y+lx/2*sin(theta)+ly/2*cos(theta)];
    
    xc = [x+0.37*lx/2*cos(theta)-0.37*ly/2*sin(theta),...
        x-0.37*lx/2*cos(theta)-0.37*ly/2*sin(theta),...
        x-0.37*lx/2*cos(theta)+0.37*ly/2*sin(theta),...
        x+0.37*lx/2*cos(theta)+0.37*ly/2*sin(theta),...
        x+0.37*lx/2*cos(theta)-0.37*ly/2*sin(theta);...
        y+0.37*lx/2*sin(theta)+0.37*ly/2*cos(theta),...
        y-0.37*lx/2*sin(theta)+0.37*ly/2*cos(theta),...
        y-0.37*lx/2*sin(theta)-0.37*ly/2*cos(theta),...
        y+0.37*lx/2*sin(theta)-0.37*ly/2*cos(theta),...
        y+0.37*lx/2*sin(theta)+0.37*ly/2*cos(theta)];
    
    plot(x,y,'o')
    line(xd(1,:),xd(2,:),'LineStyle','--','color',[0.75 0.75 1])
    line(xc(1,:),xc(2,:),'color',[0.375 0.375 0.5])
end
hold off
axis equal
set(gca,'fontsize',20)
xlim([0 ; pCon.Lx])
ylim([-pCon.Ly/2;pCon.Ly/2])
set(gca,'XTick',[0 ; pCon.Lx])
set(gca,'YTick',[-pCon.Ly/2;0;pCon.Ly/2])
set(gca,'XTickLabel',{'' ; ''})
set(gca,'YTickLabel',{'';'';''})
format_ticks(gca,{'0','L_x'},...
    {'-L_y/2','0','L_y/2'});

    